name: Release (Stable)
run-name: Creating Stable Release for ${{ github.ref_name }}

#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main
on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: "Australia/Sydney"
  LANG: "en_AU.UTF-8"
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
